language: python
python:
  - "3.6"

env:
  - DJANGO=2.1.1

# command to install dependencies
installs:
  -pip install -r requirements-travis.txt
  
# command to run tests
script: 
   -python manage.py test
