language: python
python:
  - "3.6"

# command to install dependencies
installs:
  -pip install django
  -pip install -r requirements-travis.txt

# command to run tests
scripts:
  -python manage.py test
