language: python
python:
  - "3.6"

env:
  - DJANGO=2.1.1

# command to install dependencies
installs:
  -pip install -r requirements-travis.txt
  
services:
  - postgresql


before_script:
  - psql -c 'create database test_db;' -U postgres
  - psql -c "CREATE USER mwt_user WITH PASSWORD 'password';" -U postgres


# command to run tests
script: python manage.py test
