# Generated by Django 2.1.1 on 2018-11-11 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('class_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('class_abbrev', models.CharField(max_length=4)),
                ('class_num', models.TextField(blank=True, default='', max_length=4, null=True)),
                ('class_title', models.TextField(max_length=50)),
                ('instructor', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_name', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='uni_assignment_calendar.Courses')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='events',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_assignment_calendar.Events'),
        ),
    ]
