# Generated by Django 2.1.1 on 2018-10-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_tile', models.CharField(max_length=200)),
                ('post_description', models.CharField(max_length=1000)),
                ('post_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_assignment_calendar.Post'),
        ),
    ]
