# Generated by Django 2.1.1 on 2018-11-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='due_time',
            field=models.TimeField(blank=True, default='11:59', verbose_name='Due Time'),
        ),
    ]
