# Generated by Django 2.1.1 on 2018-11-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='instructor',
            field=models.CharField(max_length=200),
        ),
    ]
