# Generated by Django 2.1.1 on 2018-11-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0002_auto_20181111_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('class_id', models.IntegerField(max_length=10)),
            ],
        ),
    ]
