# Generated by Django 2.1.1 on 2018-11-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0002_auto_20181104_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='id',
        ),
        migrations.AlterField(
            model_name='courses',
            name='class_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
