# Generated by Django 2.1.1 on 2018-12-03 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0003_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['class_title']},
        ),
    ]
