# Generated by Django 2.1.1 on 2018-11-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0003_auto_20181111_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='events',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
