# Generated by Django 2.1.1 on 2018-12-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0005_enrollment_exclude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('blacklist', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='exclude',
        ),
    ]
