# Generated by Django 2.1.1 on 2018-10-24 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0005_auto_20181021_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='post',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
