# Generated by Django 2.1.1 on 2018-12-05 16:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0007_auto_20181204_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blacklist',
        ),
        migrations.AddField(
            model_name='events',
            name='checked_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
        migrations.AddField(
            model_name='events',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='class_id',
            field=models.IntegerField(),
        ),
    ]
