# Generated by Django 2.1.1 on 2018-10-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0008_auto_20181025_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_abbrev', models.CharField(max_length=4)),
                ('class_num', models.IntegerField()),
                ('events_name', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('description', models.TextField(blank=True, help_text='Description', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
