# Generated by Django 2.1.1 on 2018-12-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0009_auto_20181205_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='checked_users',
        ),
        migrations.RemoveField(
            model_name='events',
            name='users',
        ),
    ]
