# Generated by Django 2.1.1 on 2018-10-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0009_auto_20181028_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={},
        ),
        migrations.AlterField(
            model_name='events',
            name='class_num',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
