# Generated by Django 2.1.1 on 2018-10-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0010_auto_20181028_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='class_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
