# Generated by Django 2.1.1 on 2018-10-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0011_auto_20181028_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='class_num',
            field=models.TextField(blank=True, default='', max_length=4, null=True),
        ),
    ]
