# Generated by Django 2.1.1 on 2018-12-05 19:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0012_auto_20181205_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='checked_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AddField(
            model_name='events',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='uni_assignment_calendar.Courses'),
        ),
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='due_time',
            field=models.TimeField(blank=True, default='11:59', verbose_name='Due Time'),
        ),
        migrations.AddField(
            model_name='events',
            name='events_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='events',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
