# Generated by Django 2.1.1 on 2018-10-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0013_auto_20181029_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cladd_name',
            new_name='class_name',
        ),
    ]
