# Generated by Django 2.1.1 on 2018-11-03 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0015_auto_20181103_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='events',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
