# Generated by Django 2.1.1 on 2018-11-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0017_choice'),
        ('uni_assignment_calendar', '0014_auto_20181029_1601'),
    ]

    operations = [
    ]
