# Generated by Django 2.1.1 on 2018-11-04 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0018_merge_20181104_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.RemoveField(
            model_name='events',
            name='class_abbrev',
        ),
        migrations.RemoveField(
            model_name='events',
            name='class_num',
        ),
    ]
