# Generated by Django 2.1.1 on 2018-11-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0019_auto_20181104_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField(default=0)),
                ('class_abbrev', models.CharField(max_length=4)),
                ('class_num', models.TextField(blank=True, default='', max_length=4, null=True)),
                ('class_title', models.TextField(max_length=50)),
                ('instructor', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
