# Generated by Django 2.1.1 on 2018-11-04 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni_assignment_calendar', '0020_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='uni_assignment_calendar.Courses'),
        ),
    ]
